language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install htslib samtools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt install htslib-devel samtools; fi

script:
  make && make test && make test_clean
